<a href="https://colab.research.google.com/github/chiquitoyano/Juciba/blob/master/CIPIRAN_JULIO_CESAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exámen

### Fecha entrega: Martes 12 de Julio hasta las 11:59 AM . Subir a Blackboard

### Se debe entregar en un archivo tipo jupyter-notebook (.ipynb) comprimido en un .zip o .rar
Para ello, una vez que finalice debe ir a `File` --> `Download as` --> `Notebook (.ipynb)`

[Puede ser este mismo notebook, pero recuerde cambiar el nombre del archivo como se especifica a continuación y hacer una copia para que pueda guardar los cambios]

La cátedra recuperativa es de forma individual. Coloque como nombre al archivo: Apellido_Nombre.ipynb (1 pto)

    Por favor lea bien las instrucciones de lo que se pide.

    Todos los programas deben ejecutarse con Python 3

    Por favor, limpie el código y las lineas no utilizadas - las declaraciones de impresión comentadas están bien, pero elimine cualquier otra cosa no utilizada para mantener su código fácil de leer.

Todo o nada!!

Para cualquier código que ejecute lo que no se pide, o tenga error, tiene puntaje 0. Le recomiendo leer muy bien cada enunciado y hacer las preguntas correspondientes el día sábado en la clase.

### 1a) Crear una matriz llamada “A” de 7x5 inicializada con el valor 33 (1 pts).


In [2]:
import pandas as pd
import numpy as np
A = np.full((7, 5), 33)
print(A)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


In [3]:
dimensiones=(7,5)
matriz_unos = np.ones(dimensiones)
a = matriz_unos*33
print(a)

[[33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]
 [33. 33. 33. 33. 33.]]


### 1b) Para A indicar (2 pts):  
```
    - Que tipo es (0.5 punto)
    - Que forma tiene (0.5 punto)
    - Cuantos elementos tiene (0.5 punto)
    - Que tipo de dato contiene (0.5 punto)
```

In [4]:
print(type(A))
print(A.shape)
print(A.size)
print(A.dtype)

<class 'numpy.ndarray'>
(7, 5)
35
int64


### 2) Crear una función que pida al usuario 3 números enteros y otra función min_de_tres() que sea capaz de devolver el valor menor de ellos. (4 puntos)

"Python tiene una funcion min() que no puede usar.  Usted debe ser capaz de escribirla en código"

### 3)  Crea un programa en python que logre generar una contraseña aleatorea. Para ello considere una contraseña de longitud 15 y que el programa devuelva una contraseña de esa logitud que integre : letras Mayúsculas, minúsculas, números y símbolos. (4 puntos)
Tips: puede usar la  `import random` -->  `random.choice(caracteres)`

### 4) Data Frames y pandas....

In [5]:
import pandas as pd
import io
import requests
url="https://raw.githubusercontent.com/malegria01/ACI222/main/jupyter-notebook/censo.csv"
s=requests.get(url).content
df=pd.read_csv(io.StringIO(s.decode('utf-8')))
df

ORDEN                         NOMBRE REGIÓN Código Región  \
0         0                                  PAÍS          PAÍS   
1         1                                  PAÍS          PAÍS   
2         2                                  PAÍS          PAÍS   
3         3                                  PAÍS          PAÍS   
4         4                                  PAÍS          PAÍS   
...     ...                                   ...           ...   
7629   7629  MAGALLANES Y DE LA ANTÁRTICA CHILENA            12   
7630   7630  MAGALLANES Y DE LA ANTÁRTICA CHILENA            12   
7631   7631  MAGALLANES Y DE LA ANTÁRTICA CHILENA            12   
7632   7632  MAGALLANES Y DE LA ANTÁRTICA CHILENA            12   
7633   7633  MAGALLANES Y DE LA ANTÁRTICA CHILENA            12   

      NOMBRE PROVINCIA Código Provincia     NOMBRE COMUNA Código Comuna  \
0                 PAÍS             PAÍS              PAÍS          PAÍS   
1                 PAÍS             PAÍS              PAÍS          PAÍS   
2                 PAÍS             PAÍS              PAÍS          PAÍS   
3                 PAÍS             PAÍS              PAÍS          PAÍS   
4                 PAÍS             PAÍS              PAÍS          PAÍS   
...                ...              ...               ...           ...   
7629  ÚLTIMA ESPERANZA              124  TORRES DEL PAINE         12402   
7630  ÚLTIMA ESPERANZA              124  TORRES DEL PAINE         12402   
7631  ÚLTIMA ESPERANZA              124  TORRES DEL PAINE         12402   
7632  ÚLTIMA ESPERANZA              124  TORRES DEL PAINE         12402   
7633  ÚLTIMA ESPERANZA              124  TORRES DEL PAINE         12402   

            Edad  Hombres  Mujeres     TOTAL  
0     Total País  8601989  8972014  17574003  
1          0 a 4   594059   572087   1166146  
2          5 a 9   618121   592068   1210189  
3        10 a 14   585855   561560   1147415  
4        15 a 19   636064   608633   1244697  
...          ...      ...      ...       ...  
7629     80 a 84        2        2         4  
7630     85 a 89        0        1         1  
7631     90 a 94        0        0         0  
7632     95 a 99        0        0         0  
7633   100 o más        0        0         0  

[7634 rows x 11 columns]

### Obtener datos mediante código python y 
# responder con palabras o con print lo que se pide:

#### 4a) ¿Cuál es el código de la provincia de MALLECO? (2 puntos)



In [6]:
df.columns = ['ORDEN', 'NOMBRE_REGIÓN', 'Código_Región', 'NOMBRE_PROVINCIA', 'Código_Provincia', 'NOMBRE_COMUNA', 'Código_Comuna', 'Edad', 'Hombres', 'Mujeres', 'TOTAL']
code_provincia = df.loc[(df['NOMBRE_PROVINCIA'] == 'MALLECO') & (df['NOMBRE_PROVINCIA'] == 'MALLECO')]['Código_Provincia'].unique()
print("El código de la provincia de Malleco es {}".format(code_provincia))


El código de la provincia de Malleco es ['92']


#### 4b) ¿Cuál es el código de la comuna de VICTORIA? (2 puntos)

In [7]:
code_comuna = df.loc[(df['NOMBRE_PROVINCIA'] == 'VICTORIA') & (df['NOMBRE_PROVINCIA'] == 'VICTORIA')]['Código_Comuna'].unique()
print("El código de la comuna de Victoria es {}".format(code_comuna))


El código de la comuna de Victoria es []


#### 4c) ¿A que provincia pertenece la comuna de 'HUARA'? (2 puntos)


In [8]:
code_comuna = df.loc[(df['NOMBRE_COMUNA'] == 'HUARA') ]['NOMBRE_PROVINCIA'].unique()
print("La Provincia de la comuna es: {}".format(code_comuna))


La Provincia de la comuna es: ['DEL TAMARUGAL']


#### 4d) ¿Cuántos Hombres y cuántas mujeres habitan en la comuna de 'SIERRA GORDA'? (2 puntos)

In [16]:
total = df.loc[(df['NOMBRE_COMUNA'] == 'SIERRA_GORDA')  & (df['Hombres'] == 'Total Comunal')] ['TOTAL']
total = df.loc[(df['NOMBRE_COMUNA'] == 'SIERRA_GORDA')  & (df['Mujeres'] == 'Total Comunal')] ['TOTAL']
print("total de hombres: {}")


total de hombres: {}


#### 4e) Grafique el total de hombres y mujeres de SIERRA GORDA (1 punto)

### 5) a) Crear nuevos dataframe que contenga información por nuevos tramos de edad y considerar (2 puntos) 

Grupo 1 = personas menores o iguales de 19 años (grupo menores edad) 

 Grupo 2 = personas iguales o mayores de 60 años (grupo Tercera edad)


**tips**: Es mejor eliminar todas las filas que contienen Total y Pais (buscar "loc").

In [18]:
new_df2 = df.loc[(df['Edad'].str.contains("Total") == False) & (df['NOMBRE_REGIÓN'].str.contains("PAÍS") == False)]
new_df2.head(30)
new_df3 = new_df2.loc[(new_df2['Edad'] == '0 a 4') | (new_df2['Edad'] == '5 a 9') | 
               (new_df2['Edad'] == '10 a 19') | (new_df2['Edad'] == '20 a 60')]

new_df3.head(6)


ORDEN       NOMBRE_REGIÓN Código_Región NOMBRE_PROVINCIA Código_Provincia  \
23     23  ARICA Y PARINACOTA            15            ARICA              151   
24     24  ARICA Y PARINACOTA            15            ARICA              151   
45     45  ARICA Y PARINACOTA            15            ARICA              151   
46     46  ARICA Y PARINACOTA            15            ARICA              151   
67     67  ARICA Y PARINACOTA            15       PARINACOTA              152   
68     68  ARICA Y PARINACOTA            15       PARINACOTA              152   

   NOMBRE_COMUNA Código_Comuna   Edad  Hombres  Mujeres  TOTAL  
23         ARICA         15101  0 a 4     8123     7770  15893  
24         ARICA         15101  5 a 9     8697     8347  17044  
45     CAMARONES         15102  0 a 4       32       29     61  
46     CAMARONES         15102  5 a 9       38       30     68  
67         PUTRE         15201  0 a 4       42       38     80  
68         PUTRE         15201  5 a 9       44       44     88

### 5b) Cuántas mujeres y hombres hay por cada región del grupo 2 (tercera edad). (2 puntos). 
[Tips: Cuidado con las filas que contienen Total o PAÍS]

### 5c) Grafique sus datos (1 punto) [Total hombres y mujeres Tercera Edad por Región]